server:
  port: 8080

database:
  dbname: "cvetracking"
  dbuser: "dbuser"
  dbpassword: "supersafepassword!"
  dbhostname: "0.0.0.0:3306"

cpe:
  - cpe:2.3:a:arm:mbed_tls:3.0.0
  - cpe:2.3:a:arm:mbed_tls:2.28.0
  - cpe:2.3:a:cjson_project:cjson:1.5.6
  # - cpe:2.3:o:linux:linux_kernel:5.4.110
